### ISSUE TITLE
Not compiling in Wemos D1 Mini

### ISSUE THREAD

**Issue by BMBIT-oss** [benkfra/Arduino-CoDeSys-NetVars#1]
Hi ,
I can't compile o a wemos d1 mini .
Can you please assist ? 

Also I would like to use your library on the Etherenet Modules , can you please assist I modifying this lib to work with Mega or Nano with ethernet shield ?

**Comment by benkfra** [comment]
Hello,
I have adjusted the readme. There was still an example with an old version stored. In the meantime the parameters had changed.
Please adapt your code to the new readme - then it should already work.

For further support I would need e.g. an example project with settings, if you could provide that.

Sorry for the mistake and thanks for your hint!
